BlogEngine/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BlogEngine.CodeBaseControllers;
using BlogEngine.Log;
using BlogEngine.DAL;
using BlogEngine.Models;
using BlogEngine.DTO;
using BlogEngine.BusinessLogicLayer;
//using System.Web.Routing;

namespace BlogEngine.Controllers
{
    public class BlogController : MvcBaseController
    {
        //global declarations
        public string classname = "BlogController";
        LoggingHelper logginghelper = new LoggingHelper();
        BlogEngineDAL dataaccess = null;
        BusinessLogic objBusinessLogic = null;

        //constructor
        public BlogController() : base()
        {
            dataaccess = new BlogEngineDAL();
            objBusinessLogic = new BusinessLogic();
        }

        #region Pages
        public ActionResult About()
        {
            logginghelper.Log(LoggingLevels.Info, "Class: " + classname + " :: About -Begin");
            try
            {
                ViewBag.Message = "Your application description page.";
            }
            catch (Exception ex)
            {
                logginghelper.Log(LoggingLevels.Error, "Class: " + classname + " :: About" + ex);
            }
            logginghelper.Log(LoggingLevels.Info, "Class: " + classname + " :: About -End");
            return View();
        }

        [HttpGet]
        public ActionResult Contact()
        {
            return View();
        }

        [HttpPost]
        public JsonResult Contact(ContactDTO objContact)
        {
            logginghelper.Log(LoggingLevels.Info, "Class: " + classname + " :: Contact -Begin");
            ResponseDTO res = new ResponseDTO();
            try
            {
                res.IsSucess = objBusinessLogic.SendContactMail(objContact);
            }
            catch (Exception ex)
            {
                logginghelper.Log(LoggingLevels.Error, "Class: " + classname + " :: Posts " + ex);
            }
            logginghelper.Log(LoggingLevels.Info, "Class: " + classname + " :: Contact -End");
            return Json(res, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult Subscribe()
        {
            logginghelper.Log(LoggingLevels.Info, "Class: " + classname + " :: Subscribe(HttpGet) -Begin");
            UserDropdowns objuserDropdowns = null;
            try
            {
                objuserDropdowns = new UserDropdowns(dataaccess);
            }
            catch(Exception ex)
            {
                logginghelper.Log(LoggingLevels.Error, "Class: " + classname + " :: Subscribe(HttpGet) " + ex);
            }            
            logginghelper.Log(LoggingLevels.Info, "Class: " + classname + " :: Subscribe(HttpGet) -End");
            return View(objuserDropdowns);
        }

        [HttpPost]
        public JsonResult Subscribe(User objUser)
        {
            logginghelper.Log(LoggingLevels.Info, "Class: " + classname + " :: Subscribe(HttpPost) -Begin");
            ResponseDTO response = null;
            try
            {
                response = dataaccess.SaveUser(objUser);
            }
            catch (Exception ex)
            {
                logginghelper.Log(LoggingLevels.Error, "Class: " + classname + " :: Subscribe(HttpPost) " + ex);
            }
            logginghelper.Log(LoggingLevels.Info, "Class: " + classname + " :: Subscribe(HttpPost) -End");
            return Json(response,JsonRequestBehavior.AllowGet);
        }
        public ViewResult category(string catUrlSlug, int p = 1)
        {
            logginghelper.Log(LoggingLevels.Info, "Class: " + classname + " :: Category - Begin");
            ListViewModel viewModel = null;
            try
            {
                viewModel = new ListViewModel(dataaccess, catUrlSlug, p,"Category");
                if (viewModel.Category == null)
                    throw new HttpException(404, "Category Not Found");
                ViewBag.Title = String.Format(@"Latest posts on category ""{0}""", viewModel.Category.CategoryName);
            }
            catch (Exception ex)
            {
                logginghelper.Log(LoggingLevels.Error, "Class: " + classname + " :: Category " + ex);
            }
            logginghelper.Log(LoggingLevels.Info, "Class: " + classname + " :: Category - End");
            return View("List", viewModel);
        }

        #endregion Pages

        public ViewResult tag(string tagSlug, int tp = 1)
        {
            logginghelper.Log(LoggingLevels.Info, "Class: " + classname + " :: Tag - Begin");
            ListViewModel viewModel = null;
            try
            {
                viewModel = new ListViewModel(dataaccess, tagSlug, tp, "Tag");
                if (viewModel.Tag == null)
                    throw new HttpException(404, "Tag Not Found");
                ViewBag.Title = String.Format(@"Latest posts on Tag ""{0}""", viewModel.Tag.TagName);
            }
            catch(Exception ex)
            {
                logginghelper.Log(LoggingLevels.Error, "Class: " + classname + " :: Tag " + ex);
            }
            logginghelper.Log(LoggingLevels.Info, "Class: " + classname + " :: Tag - End");
            return View("List", viewModel);
        }

        #region Search

        [HttpGet]
        public ViewResult Search()
        {
            return View();
        }

        [HttpPost]
        public ViewResult Search(FormCollection form)
        {
            logginghelper.Log(LoggingLevels.Info, "Class: " + classname + " :: Search[HttpPost] - Begin");
            string searchText = form["txtPostSearch"].ToString().Trim();
            ListViewModel viewModel = null;
            try
            {
                if (!string.IsNullOrEmpty(searchText))
                {
                    viewModel = new ListViewModel(dataaccess, searchText, 1, "Search");
                    ViewBag.Title = String.Format(@"Lists of posts found for search text ""{0}""", searchText);
                    ViewBag.PreviousPage = "SEARCH";                    
                }
            }
            catch(Exception ex)
            {
                logginghelper.Log(LoggingLevels.Error, "Class: " + classname + " :: Search[HttpPost] " + ex);
            }
            logginghelper.Log(LoggingLevels.Info, "Class: " + classname + " :: Search[HttpPost] - End");
            if (!string.IsNullOrEmpty(searchText))
                return View("List", viewModel);
            else
                return View();            
        }

        #endregion Search

        #region Posts

        public ViewResult Posts(int page = 1)
        {
            logginghelper.Log(LoggingLevels.Info, "Class: " + classname + " :: Posts -Begin");
            ListViewModel viewModel = null;
            try
            {
                viewModel = new ListViewModel(dataaccess, page);
                ViewBag.PreviousPage = "HOME";
            }
            catch (Exception ex)
            {
                logginghelper.Log(LoggingLevels.Error, "Class: " + classname + " :: Posts " + ex);
            }
            logginghelper.Log(LoggingLevels.Info, "Class: " + classname + " :: Posts -End");
            return View("List", viewModel);
        }

        //Get post by post urlslug
        public ViewResult Post(string urlslug)
        {
            logginghelper.Log(LoggingLevels.Info, "Class: " + classname + " :: Post - Begin");
            Post post = null;
            try
            {
                post = dataaccess.Post(urlslug,null);
                post.PostNavDetails = dataaccess.GetNextAndPreviousPostIds(post.PostId);
                User objuser = dataaccess.GetUserList().Where(x => x.UserId.Equals(post.UserId)).FirstOrDefault();
                ViewBag.AuthorName = objuser.FirstName + " " + objuser.LastName;
                if (post == null)
                    throw new HttpException(404, "Post Not Found");
                else if (post.IsPublished == false && User.Identity.IsAuthenticated==false)
                    throw new HttpException(401, "Post Not Published");
            }
            catch(Exception ex)
            {
                logginghelper.Log(LoggingLevels.Error, "Class: " + classname + " :: Post " + ex);
            }
            logginghelper.Log(LoggingLevels.Info, "Class: " + classname + " :: Post - End");
            return View(post);
        }

        //Get post by postId
        public ViewResult PostById(long postId)
        {
            logginghelper.Log(LoggingLevels.Info, "Class: " + classname + " :: Post - Begin");
            Post post = null;
            try
            {
                post = dataaccess.Post(null, postId);
                post.PostNavDetails = dataaccess.GetNextAndPreviousPostIds(post.PostId);
                User objuser = dataaccess.GetUserList().Where(x => x.UserId.Equals(post.UserId)).FirstOrDefault();
                ViewBag.AuthorName = objuser.FirstName + " " + objuser.LastName;
                if (post == null)
                    throw new HttpException(404, "Post Not Found");
                else if (post.IsPublished == false && User.Identity.IsAuthenticated == false)
                    throw new HttpException(401, "Post Not Published");
            }
            catch (Exception ex)
            {
                logginghelper.Log(LoggingLevels.Error, "Class: " + classname + " :: Post " + ex);
            }
            logginghelper.Log(LoggingLevels.Info, "Class: " + classname + " :: Post - End");
            return View("Post",post);
        }

        #endregion Posts

        #region Sidebars

        [ChildActionOnly]
        public PartialViewResult Sidebars()
        {
            logginghelper.Log(LoggingLevels.Info, "Class: " + classname + " :: Sidebars - Begin");
            WidgetViewModel widgetviewmodel = null;
            try
            {
                widgetviewmodel = new WidgetViewModel(dataaccess);

BlogEngine/Views/Shared/_BlogLayout.cshtml
<!DOCTYPE html>
<!--[if lt IE 9 ]><html class="no-js oldie" lang="en"> <![endif]-->
<!--[if IE 9 ]><html class="no-js oldie ie9" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!-->
<html class="no-js" lang="en">
<!--<![endif]-->

<head>

    <!--- basic page needs
    ================================================== -->
    <title>@ViewBag.Title</title>

    <!--meta tag section for blog begin-->
    <meta charset="utf-8" />
    <meta name="author" content="raviteja swayampu" />
    <meta name="language" content="en-us" />
    <meta name="country" content="India" />

    <!-- mobile specific metas
    ================================================== -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSS
    ================================================== -->
    <link href="~/Content/themes/Hola10/css/base.css" rel="stylesheet" />
    <link href="~/Content/themes/Hola10/css/vendor.css" rel="stylesheet" />
    <link href="~/Content/themes/Hola10/css/main.css" rel="stylesheet" />

    <!-- script
    ================================================== -->
    <script src="~/Content/themes/Hola10/js/modernizr.js"></script>
    <script src="~/Content/themes/Hola10/js/pace.min.js"></script>    

    <!-- Jquery and JqueryUI
    ================================================== -->
    <script src="~/Content/themes/Hola10/js/jquery-3.2.1.min.js"></script>    
    <link href="~/Content/jquery-ui-1.12.1.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-ui.1.12.1.js"></script>

    <!-- sweet alert
    ================================================== -->    
    <link href="~/Scripts/sweetalert/sweetalert.css" rel="stylesheet" />
    <script src="~/Scripts/sweetalert/sweetalert.min.js"></script>    

    <!-- favicons
    ================================================== -->
    <link rel="shortcut icon" href="~/Content/themes/Hola10/favicon.ico" type="image/x-icon">
    <link rel="icon" href="~/Content/themes/Hola10/favicon.ico" type="image/x-icon">       

    <script type="text/javascript">
        var HostAddress = "@ConfigurationManager.AppSettings["WebHostAddress"].ToString()";
    </script>

</head>
@using System.Configuration
@{
    string webhostUrl = ConfigurationManager.AppSettings["WebHostAddress"].ToString();
}
<body id="top">

    <!-- header
    ================================================== -->
    <header class="s-header">

        <div class="header-logo">
            <a class="site-logo" href="@webhostUrl"><img src="~/Content/themes/Hola10/images/logo.png" alt="Homepage"></a>            
        </div>

        <nav class="header-nav-wrap">
            <ul class="header-nav">
                <li class="current"><a href="@webhostUrl" title="home">Home</a></li>                                               
                <li><a href="@Url.Action("Contact","Blog")" title="contact">Contact</a></li>
                <li><a href="@Url.Action("Search","Blog")" title="Search">Search</a></li>    
                <li></li>
            </ul>           
        </nav>

        <a class="header-menu-toggle" href="#0"><span>Menu</span></a>

    </header> <!-- end s-header -->
    
    <!-- home
    ================================================== -->
      
    <!-- RenderBody
    ================================================== -->
    @RenderBody()
       
    <!-- footer
    ================================================== -->
    <footer>
        <div class="row">
            <div class="col-full">

                <div class="footer-logo">
                    <a class="footer-site-logo" href="#0"><img src="~/Content/themes/Hola10/images/logo.png" alt="Homepage"></a>
                </div>

                <ul class="footer-social">
                    <li>
                        <a href="#0">
                            <i class="im im-facebook" aria-hidden="true"></i>
                            <span>Facebook</span>
                        </a>
                    </li>
                    <li>
                        <a href="#0">
                            <i class="im im-twitter" aria-hidden="true"></i>
                            <span>Twitter</span>
                        </a>
                    </li>
                    <li>
                        <a href="#0">
                            <i class="im im-instagram" aria-hidden="true"></i>
                            <span>Instagram</span>
                        </a>
                    </li>
                    <li>
                        <a href="#0">
                            <i class="im im-behance" aria-hidden="true"></i>
                            <span>Behance</span>
                        </a>
                    </li>
                    <li>
                        <a href="#0">
                            <i class="im im-pinterest" aria-hidden="true"></i>
                            <span>Pinterest</span>
                        </a>
                    </li>
                </ul>

            </div>
        </div>

        <div class="row footer-bottom">

            <div class="col-twelve">
                <div class="copyright">
                    <span>© Copyright 2019</span>
                    <span>Design by <a target="_blank" href="http://localhost/BlogEngine/Security/Login">BlogEngine</a></span>
                </div>

                <div class="go-top">
                    <a class="smoothscroll" title="Back to Top" href="#top"><i class="im im-arrow-up" aria-hidden="true"></i></a>
                </div>
            </div>

        </div> <!-- end footer-bottom -->

    </footer> <!-- end footer -->
    <!-- photoswipe background
    ================================================== -->
    <div aria-hidden="true" class="pswp" role="dialog" tabindex="-1">

        <div class="pswp__bg"></div>
        <div class="pswp__scroll-wrap">

            <div class="pswp__container">
                <div class="pswp__item"></div>
                <div class="pswp__item"></div>
                <div class="pswp__item"></div>
            </div>

            <div class="pswp__ui pswp__ui--hidden">
                <div class="pswp__top-bar">
                    <div class="pswp__counter"></div><button class="pswp__button pswp__button--close" title="Close (Esc)"></button> <button class="pswp__button pswp__button--share" title="Share"></button> <button class="pswp__button pswp__button--fs" title="Toggle fullscreen"></button> <button class="pswp__button pswp__button--zoom" title="Zoom in/out"></button>
                    <div class="pswp__preloader">
                        <div class="pswp__preloader__icn">
                            <div class="pswp__preloader__cut">
                                <div class="pswp__preloader__donut"></div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="pswp__share-modal pswp__share-modal--hidden pswp__single-tap">
                    <div class="pswp__share-tooltip"></div>
                </div><button class="pswp__button pswp__button--arrow--left" title="Previous (arrow left)"></button> <button class="pswp__button pswp__button--arrow--right" title="Next (arrow right)"></button>
                <div class="pswp__caption">
                    <div class="pswp__caption__center"></div>
                </div>
            </div>

        </div>

    </div><!-- end photoSwipe background -->

    <div id="preloader">
        <div id="loader"></div>
    </div>    

    <!-- Java Script
    ================================================== -->    
    <script src="~/Content/themes/Hola10/js/plugins.js"></script>
    <script src="~/Content/themes/Hola10/js/main.js"></script>

    <!-- addthis code 
        Go to www.addthis.com/dashboard to customize your tools
    ================================================== -->   
    <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-557ebd12296addc3"></script>
</body>

</html>

BlogEngine/Views/Shared/_BlogLayout_old.cshtml
<!DOCTYPE html>
<html>
<head>   
    <title>@ViewBag.Title</title>
    <!--meta tag section for blog begin-->
    <meta name="viewport" content="width=device-width,initial-scale=1" />    
    <meta name="author" content="raviteja swayampu" />
    <meta name="language" content="en-us" />    
    <!--meta tag section for blog begin-->

    <!-- Stylesheets -->
    <link rel="stylesheet" type="text/css" href="~/Content/themes/simple/style.css" />
    <script src="~/Scripts/jquery-3.2.1.min.js"></script>
</head>
@using System.Configuration
@{
    string webhostUrl = ConfigurationManager.AppSettings["WebHostAddress"].ToString();
}
<body>
    <div id="main">

        <!-- Header -->
        <div id="header">
            <div id="logo">
                <div id="logo_text">
                    <h1><a href="@webhostUrl">Blog<span class="logo_colour">Engine</span></a></h1>
                    <h2>Writings, Experiments and More...</h2>
                </div>
            </div>

            <!-- Navigation -->
            <div id="menubar">
                <ul id="menu">
                    <li><a href="@webhostUrl">Posts</a></li>
                    <li>@Html.ActionLink("Contact","Contact","Blog")</li>
                    <li>@Html.ActionLink("AboutMe","AboutMe","Blog")</li>
                </ul>
            </div>

        </div>

        <!-- Site Content -->
        <div id="site_content">
            @Html.Partial("_Search")
            @RenderBody()

            @*Calls to render sidebar*@
            @Html.Action("Sidebars")
        </div>

        <!-- Footer -->
        <div id="footer">
            Copyright ï¿½ @DateTime.Now.Year BlogEngine All Rights Reserved
        </div>
    </div>
</body>
</html>

BlogEngine/Views/Shared/_Categories.cshtml
@model List<BlogEngine.DTO.Category>

<div class="sidebar">
    <h3>Categories</h3>
    @{
        if(Model.Count>0)
        {
            <ul>
                @foreach (var category in Model)
                {
                    <li>@Html.CategoryLink(category)</li>
                }
            </ul>
        }
        else
        {
            <p>No Categories found!</p>
        }
    }
</div>

BlogEngine/Views/Shared/_Pager.cshtml
@using System.Configuration
@model BlogEngine.Models.ListViewModel

@* Read the current page and total pages *@
@{
    int postsCountInHomePage = Convert.ToInt32(ConfigurationManager.AppSettings["NumberOfPostsOnHomePage"].ToString());
    var totalPages = Math.Ceiling((double)Model.TotalPosts / postsCountInHomePage);
}
<!-- Pagination for Home page -->
@if (Model.PageNo > 1 || Model.PageNo < totalPages)
{
    string webhostUrl = ConfigurationManager.AppSettings["WebHostAddress"].ToString();
    if (Model.isHomePage == true)
    {
        var _previous = string.Format("/page/{0}", Model.PageNo - 1);
        var _next = string.Format("/page/{0}", Model.PageNo + 1);

        <div class="pager">
            <!--Home page pagination links-->
            <a href="@webhostUrl@_previous" title="Previous" class="btn btn--stroke float-left"
               style="visibility:@(Model.PageNo > 1 ? "visible" : "collapse")"><< previous</a>
            <a href="@webhostUrl@_next" title="Next" class="btn btn--stroke float-right"
               style="visibility:@(Model.PageNo < totalPages ? "visible" : "collapse")">next >></a>
        </div>
    }
    else
    {
        int _previd = Model.PageNo - 1;
        int _nextid = Model.PageNo + 1;
        if (Model.Category != null)
        {
            <div class="pager">
                <!--Home page pagination links-->
                <a href="@Url.Action("category", "Blog", new
                    {
                        catUrlSlug = Model.Category.CategoryUrlSlug,
                        p = _previd
                    })" title="Previous" class="btn btn--stroke float-left"
                   style="visibility:@(Model.PageNo > 1 ? "visible" : "collapse")"><< previous</a>
                <a href="@Url.Action("category", "Blog", new
                    {
                        catUrlSlug = Model.Category.CategoryUrlSlug,
                        p = _nextid
                    })" title="Next" class="btn btn--stroke float-right"
                   style="visibility:@(Model.PageNo < totalPages ? "visible" : "collapse")">next >></a>
            </div>
        }
        else if (Model.Tag != null)
        {
            <div class="pager">
                <!--Home page pagination links-->
                <a href="@Url.Action("tag", "Blog", new
                    {
                        tagSlug = Model.Tag.TagUrlSlug,
                        tp = _previd
                    })" title="Previous" class="btn btn--stroke float-left"
                   style="visibility:@(Model.PageNo > 1 ? "visible" : "collapse")"><< previous</a>
                <a href="@Url.Action("tag", "Blog", new
                    {
                        tagSlug = Model.Tag.TagUrlSlug,
                        tp = _nextid
                    })" title="Next" class="btn btn--stroke float-right"
                   style="visibility:@(Model.PageNo < totalPages ? "visible" : "collapse")">next >></a>
            </div>
        }
        else
        {
            <div class="pager">
                <!--Home page pagination links-->
                <a href="@Url.Action("Search", "Blog", new
                    {
                        s = Model.Search,
                        p = _previd
                    })" title="Previous" class="btn btn--stroke float-left"
                   style="visibility:@(Model.PageNo > 1 ? "visible" : "collapse")"><< previous</a>
                <a href="@Url.Action("Search", "Blog", new
                    {
                        s = Model.Search,
                        p = _nextid
                    })" title="Next" class="btn btn--stroke float-right"
                   style="visibility:@(Model.PageNo < totalPages ? "visible" : "collapse")">next >></a>
            </div>
        }
    }
}

BlogEngine/Views/Shared/_PostTemplate.cshtml
@using System.Globalization
@model BlogEngine.DTO.Post

@{
    DateTime dt = new DateTime();
    dt = Convert.ToDateTime(Model.PostedOn);
}

<article class="col-block">
    <div class="blog-date">        
        <a href="blog-single.html">@CultureInfo.CurrentCulture.DateTimeFormat.GetMonthName(dt.Month) @dt.Day, @dt.Year</a>
    </div>
    <h2 class="h01">
        @Html.PostLink(Model)
    </h2>
    <p>
        @Model.PostMeta
    </p>
    <div class="blog-cat">
        @Html.CategoryLink(Model.Category)        
    </div>
</article>

BlogEngine/Views/Shared/_RecentPosts.cshtml
@model List<BlogEngine.DTO.Post>

<div class="sidebar">
    <h3>Recent Posts</h3>
    @if (Model.Count > 0)
    {
        <ul>
        @foreach (var post in Model)
        {
            <li>@Html.PostLink(post)</li>
        }
        </ul>
    }
    else
    {
        <p>No posts found!</p>
    }
</div>

BlogEngine/Views/Shared/_Search.cshtml
@using (Html.BeginForm("Search", "Blog", FormMethod.Get, new
{
    id = "search-form"
}))
{
    <p>@Html.TextBox("s")</p>
    <p><input type="button" id="btnSearch" value="Search" /></p>
}    

<script type="text/javascript">
    $(document).ready(function () {
        $("#btnSearch").click(function () {
            if ($("#s").val().trim() != "") {
                $("#search-form").submit();
            }
            else
                $("#s").css("border-color", "red");
        });

        $("#s").focus(function () {
            $("#s").css("border-color", "");
        });
    });
</script>

BlogEngine/Views/Shared/_Sidebars.cshtml
@model BlogEngine.Models.WidgetViewModel

<div id="sidebars">
    @Html.Partial("_Categories",Model.Categories)

    @*@Html.Partial("_Tags",Model.Tags)*@

    @Html.Partial("_RecentPosts",Model.LatestPosts)
</div>

BlogEngine/Views/Shared/_Tags.cshtml
@model List<BlogEngine.DTO.Tag>

<div class="tags sidebar">
    <h3>Tags</h3>
    @if (Model.Count > 0)
    {
        foreach (var tag in Model)
        {
            @Html.TagLink(tag)        
        }
    }
    else
    {
        <p>No Tags found!</p>
    }
</div>